apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
type: Opaque
# values from stringData are converted by means of base64 to data
stringData:
  AWS_ACCESS_KEY_ID: "local"
  AWS_SECRET_ACCESS_KEY: "local"
