apiVersion: v1
kind: Pod
metadata:
  name: database-pod
  labels:
    component: db
spec:
  containers:
    - name: example-api-database
      env:
        - name: POSTGRES_DB
          value: example-api
        - name: POSTGRES_USER
          value: root
        - name: POSTGRES_PASSWORD
          value: root
        - name: TZ
          value: America/Sao_Paulo
        - name: PGTZ
          value: America/Sao_Paulo
      image: postgres:13
      imagePullPolicy: "IfNotPresent"
      ports:
        - containerPort: 5432
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgredb-data
          subPath: postgres
  volumes:
    - name: postgredb-data
      persistentVolumeClaim:
        claimName: db-pv-claim
