apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: api-replicaset
  labels:
    component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: example-api
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root
            - name: DB_URL
              value: database:5432/example-api
          image: demo-registry:5000/example-api:0.1.0
          imagePullPolicy: IfNotPresent
          command: 
            - sh
            - -c
          args:
            - "dockerize -wait tcp://database.$(POD_NAMESPACE).svc.cluster.local:5432 -timeout 20s java -jar api.jar"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 120
            periodSeconds: 120
            timeoutSeconds: 15
            httpGet:
              path: /
              port: 80
          readinessProbe:
            initialDelaySeconds: 100
            periodSeconds: 15
            timeoutSeconds: 15
            httpGet:
              path: /
              port: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
