apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    component: db
spec:
  # ClusterIP is a default value, may be omitted
  type: ClusterIP
  ports:
   - port: 5432
  selector:
    component: db
