apiVersion: batch/v1
kind: Job
metadata:
  name: db-backup
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: db-backup
        envFrom:
          - configMapRef:
              name: db-config
        env:
          - name: MODE
            value: MANUAL
          - name: MANUAL_RUN_FOREVER
            value: "FALSE"
          - name: CONTAINER_ENABLE_SCHEDULING
            value: "FALSE"
          - name: CONTAINER_ENABLE_MONITORING
            value: "FALSE"
          - name: BACKUP_LOCATION
            value: S3
          - name: S3_HOST
            value: minio:9000
          - name: S3_PROTOCOL
            value: http
          - name: S3_REGION
            # this is just to meet the requirements
            value: us-east-1
          - name: S3_PATH
            value: ''
          - name: S3_BUCKET
            value: backups
          - name: S3_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: rootUser
          - name: S3_KEY_SECRET
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: rootPassword
          - name: DB_TYPE
            value: pgsql
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
        image: tiredofit/db-backup:3.4.2
        command:
          - backup-now
      restartPolicy: Never
