apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
data:
  servers.json: |
    {
        "Servers": {
          "1": {
            "Name": "Example API PostgreSQL DB",
            "Group": "Servers",
            "Port": 5432,
            "Username": "root",
            "Host": "database.example-api.svc.cluster.local",
            "SSLMode": "prefer",
            "MaintenanceDB": "example-api"
          }
        }
    }
