apiVersion: acid.zalan.do/v1
kind: postgresql

metadata:
  name: acid-pg-demo
  namespace: example-api
  labels:
    team: acid

spec:
  teamId: acid
  postgresql:
    version: "14"
  numberOfInstances: 3
  enableConnectionPooler: true
  volume:
    size: 1Gi
  users:
    testuser: []
  databases:
    testdb: testuser
  allowedSourceRanges: []
    # IP ranges to access your cluster go here

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 1000Mi
